title: Arthur Aires # your name (or website title) here
logo: "/images/me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Python programmer and an information security enthusiast.<br>
  I study medicine at the Federal University of Amapá.
  <br>
  <a href="http://arquivopessoa.net/textos/163">Tenho em mim todos os sonhos do mundo <3.</a>
  <br>
  <a href="https://www.facebook.com/arthur.oliveira.25/"><img height="30px" src="/icones/fb.png?"></a>
  <a href="https://www.instagram.com/airesflac/"><img  height="30px" src="/icones/instagram.png?"></a>
  <a href="https://www.twitter.com/projetodehasker"><img height="30px" src="/icones/twitter.png?"></a>
  <a href="mailto:me@arthurair.es"><img height="30px" src="/icones/mail.png?"></a>
  <a href="https://github.com/arthur4ires"><img height="30px" src="/icones/github.png?"></a>
  <br>  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
