title: Arthur Aires # your name (or website title) here
logo: "/images/me.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Tenho em mim todos os sonhos do mundo - Alvaro de Campos
  <br><br>
  <a href="https://www.facebook.com/arthur.oliveira.25/">Facebook</a>  
  <br><br>
  <a href="https://www.instagram.com/airesflac/">Instagram</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
